APP_NAME: "e_commerce"
APP_PORT: "8004"

DB_DRIVER: "mysql"
DB_HOST: "localhost"
DB_PORT: 3306
DB_NAME: "e_commerce" 
DB_USER: "rushi"
DB_PASSWORD: "rushi@1234"
DB_MAX_POOL_SIZE: 5
DB_MAX_OPEN_CONS: 5
DB_MAX_LIFE_TIME_MINS: 30
MIGRATION_PATH: ".././migrations"